name: ganspace
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - cudatoolkit=11.8
  - pillow=6.2
  - ffmpeg
  - tqdm
  - scipy
  - scikit-learn
  - scikit-image
  - boto3
  - requests
  - nltk
  - pip
  - pip:
    - fbpca
    - pyopengltk

# conda env update -f environment.yml --prune
